### ISSUE TITLE
zkt is using grep instead of ripgrep

### ISSUE THREAD

**Issue by sleeping-barber** [sirupsen/zk#12]
Hi,

is it on purpose that `zkt` is using `ggrep` here instead of `rg`?

https://github.com/sirupsen/zk/blob/ab20c80e71423a425d42bc72366232c9dadbaf8c/bin/zkt#L7

I am running `zk` on macOS and the README didn't mention it to install GNU grep.

Cheers

**Comment by sirupsen** [comment]
Nah, should be changed, PR would be great
