### ISSUE TITLE
A toolset inspired by zk

### ISSUE THREAD

**Issue by randrej** [sirupsen/zk#17]
I've developed a set of UNIX-philosophy CLI utilities for managing your zettelkasten, a C++ library (used by the utilities) and a set of shell scripts that makes the whole thing easy to use for the terminal-savvy. 
It's divided into a set of CLI utilities with consistent, UNIX-like interfaces, and a set of scripts that implement the fzf-based picker functionality.
It's all heavily inspired by this project, just faster, more consistent, more docs. Feel free to check it out, maybe also link (I link to this page).

utilities + lib: https://gitlab.com/andrejr/zetk  
shell wrappers: https://gitlab.com/andrejr/zetk_fzf

**Comment by sirupsen** [comment]
Very cool, congratulations on the release :)

I've recently been working on a FTS tool myself written in Rust... pretty fun to write as an alternative to the sqlite based one!
