### ISSUE TITLE
Any plans on supporting nested directories?

### ISSUE THREAD

**Issue by NightMachinery** [sirupsen/zk#8]

**Comment by sirupsen** [comment]
Why do you want nested directories over tags?

**Comment by NightMachinery** [comment]
[**@sirupsen**](https://github.com/sirupsen) commented on [Aug 2, 2020, 5:41 PM GMT+4:30](https://github.com/sirupsen/zk/issues/8#issuecomment-667672392 "2020-08-02T13:11:24Z - Replied by Github Reply Comments"):
> Why do you want nested directories over tags?

Because directories are ubiquitously supported (e.g., in my iOS git app), and tags need special support. Also, dirs can act as tags easily:
![image](https://user-images.githubusercontent.com/36224762/89123895-14854180-d4e8-11ea-88b0-65280280a1c5.png)


Anyhow, feel free to ignore this, I am reaching the conclusion that building my notes software myself is the best solution.

**Comment by sirupsen** [comment]
Yeah, I don't think I'll be doing this in the near future. I recommend building your own, for sure, I expect most people to copy the ideas more than the source from here :)
